{% set name = "pulpy" %}
{% set version = "1.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 10f4991d93dbd7a3a4d7f2fcc83faf5ae8203349655ddac0098c71acc59216db

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - folium
    - ipyleaflet
    - pyshp
    - python >=3.8

test:
  imports:
    - pulpy

about:
  home: "https://github.com/jonbmartin/pulpy"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "PulPy- Pulses in Python"
  dev_url: https://github.com/jonbmartin/pulpy

extra:
  recipe-maintainers:
    - jonbmartin